# playbooks/vars.yml
routers:
  router0:
    hostname: router0
    interfaces:
      - name: Ethernet0/0
        ip: 192.168.0.10
        mask: 255.255.255.0
      - name: Ethernet0/1
        ip: 10.0.0.1
        mask: 255.255.255.0
  router1:
    hostname: router1
    interfaces:
      - name: FastEthernet0/0
        ip: 10.0.1.2
        mask: 255.255.255.0
  router2:
    hostname: router2
    interfaces:
      - name: FastEthernet0/0
        ip: 10.0.2.2
        mask: 255.255.255.0
